name: Lint & Tests

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Install deps
        working-directory: ${{ inputs.context }}
        run: npm ci
 
      - name: Linting
        working-directory: ${{ inputs.context }}
        run: npm run lint
 
      - name: Tests
        working-directory: ${{ inputs.context }}
        run: npm run test
