name: Deploy
 
on:
  push:
    branches: [ main ]
 
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_context: ${{ steps.set-context.outputs.context }}
    steps:
      - uses: actions/checkout@v3
 
      - name: Detect changed services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
 
      - name: Set changed context
        id: set-context
        run: |
          if [[ "${{ steps.filter.outputs.frontend }}" == "true" ]]; then
            echo "context=frontend" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.filter.outputs.backend }}" == "true" ]]; then
            echo "context=backend" >> $GITHUB_OUTPUT
          else
            echo "context=none" >> $GITHUB_OUTPUT
          fi

  checks:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed_context != 'none'
    uses: ./.github/workflows/checks.yaml
    with:
      context: ${{ needs.detect-changes.outputs.changed_context }}

  build:
    needs:
      - detect-changes
      - checks
    if: needs.detect-changes.outputs.changed_context != 'none'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/devops-${{ needs.detect-changes.outputs.changed_context }}:${{ github.sha }} ./${{ needs.detect-changes.outputs.changed_context }}
          docker push ${{ secrets.DOCKER_USER }}/devops-${{ needs.detect-changes.outputs.changed_context }}:${{ github.sha }}
